---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-postgresql
  labels:
    app.kubernetes.io/name: dataverse-postgresql
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  username: dataverse
  password: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-doi
  labels:
    app.kubernetes.io/name: dataverse-doi
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  username: test.doi
  password: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-api
  labels:
    app.kubernetes.io/name: dataverse-api
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  key: supersecret
---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-admin
  labels:
    app.kubernetes.io/name: dataverse-admin
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  password: admin1
