---
version: '3.5'
services:

  postgresql:
    image: library/postgres:10.13
    restart: unless-stopped
    environment:
      - "LC_ALL"
      - "POSTGRES_DB=dataverse"
      - "POSTGRES_USER=dataverse"
      - "POSTGRES_PASSWORD=changeme"
      - "POSTGRES_PORT=5432"
    env_file: .env
    expose:
      - 5432

  solr:
    image: iqss/solr-k8s
    expose:
      - 8983

  dataverse:
    user:
      "root"
    build:
      context: .
      dockerfile: ./docker/dataverse-k8s/payara/Dockerfile
    depends_on:
      - postgresql
      - solr
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - type: bind
        source: ./personas/docker-compose/secrets
        target: /secrets
        #read_only: true
