---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - configmap.yaml
  - pvc.yaml
  - svc.yaml

images:
  - name: iqss/dataverse-k8s
    newTag: "4.19"
